remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: JayB-127's Page
description: Hi. Welcome to my GitHub page, hosting all things including info about me and my projects...
